[package]
name = "celestedebugrc"
description = "Client for interacting with Everest DebugRC"
license.workspace = true
repository.workspace = true
version.workspace = true
edition = "2021"

[dependencies]
ureq = { version = "3.1", default-features = false }
anyhow = "1.0"
