[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
license = "MIT"
repository = "https://github.com/jakobhellermann/celestetools"

[profile.dev.package."*"]
opt-level = 2

[profile.release]
debug = true
