[package]
name = "celesteloader"
version = "0.1.0"
edition = "2021"

[dependencies]
unicase = "2.7.0"
zip = { version = "0.6", default-features = false, features = ["deflate"] }

[dev-dependencies]
anyhow = "1.0"