[package]
name = "celesteloader"
version = "0.1.0"
edition = "2021"

[dependencies]
unicase = "2.7.0"
zip = { version = "0.6", default-features = false, features = ["deflate"] }

[target.'cfg(target_os="windows")'.dependencies]
winreg = "0.52"

[target.'cfg(not(target_os="windows"))'.dependencies]
dirs = "5.0"

[dev-dependencies]
anyhow = "1.0"
