[package]
name = "celesterender"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
celesteloader = { path = "../celesteloader" }
elsa = "1.10"
fastrand = "2.0"
roxmltree = "0.19"
serde-roxmltree = "0.7"
tiny-skia = "0.11"

[dev-dependencies]
mlua = { version = "0.9", features = ["lua54", "vendored"] }
